#!/bin/bash
#This script is to install ANTLR (if you don't already have it) so you can run the "Micro" bash script.
#This file MUST be run by using "source ./InstallANTLR"
cd /usr/local/lib
curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
export CLASSPATH=".:/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH"
cd -
